name: Basic API Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest


    strategy:
      fail-fast: false
      matrix:
        marker: [ smoke, sanity]


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt


      - name: Run tests in parallel with pytest
        run: pytest -v tests/${{ matrix.marker }}

